spring:
  application:
    name: chain-extractor

  # Kafka 配置
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # 消息序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 提高吞吐量的批处理配置 (可选但推荐)
      batch-size: 16384
      buffer-memory: 33554432
      retries: 3

  # PostgreSQL 配置 (对应你 docker-compose 里的 citus-master)
  datasource:
    url: jdbc:postgresql://localhost:5432/chain_pipline
    username: postgres
    password: 63382212
    driver-class-name: org.postgresql.Driver

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 如果你有 xml 的话，目前我们用的注解，这行可有可无
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换